apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: kol-platform
type: Opaque
data:
  jwt-secret: eW91ci1qd3Qtc2VjcmV0 # base64 encoded
  jwt-refresh-secret: eW91ci1yZWZyZXNoLXNlY3JldA== # base64 encoded
  youtube-api-key: eW91ci15b3V0dWJlLWFwaS1rZXk= # base64 encoded
  stripe-secret-key: c2tfdGVzdF95b3VyLXN0cmlwZS1zZWNyZXQ= # base64 encoded
  stripe-webhook-secret: d2hzZWNfeW91ci13ZWJob29rLXNlY3JldA== # base64 encoded

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: kol-platform
data:
  NODE_ENV: "production"
  PORT: "8000"
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/kol_platform"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kol-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/kol-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-refresh-secret
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: youtube-api-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: stripe-webhook-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kol-platform
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: kol-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80